[package]
name = "restaurant"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "restaurant"


[dependencies]
rand = "0.8.5"
uuid = { version = "1.10.0", features = ["v4"] }
